#include <iostream>
#include <Windows.h>
using namespace std;

int main() {
      SetConsoleCP(1251);
      SetConsoleOutputCP(1251);
      HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
      SetConsoleTextAttribute(hConsole, 14);
      cout << "\"Hello, World!\"" << endl;
      SetConsoleTextAttribute(hConsole, 15);
      cout << "/Bjarne Stroustrup/" << endl;
      cout << "Hello, World!" << endl;
      cout << "\\\\Dennis Ritchi\\\\" << endl;
      cout << "To be,";
      SetConsoleTextAttribute(hConsole, 13);
      cout << " or not ";
      SetConsoleTextAttribute(hConsole, 15);
      cout << "to be: that is the question:" << endl;
      cout << "Whether ";
      SetConsoleTextAttribute(hConsole, 14);
      cout << "\'tis nobler in the mind to suffer" << endl;
      cout << "The slings and arrows of outrageous fortune," << endl;
      cout << "Or to take arms against a sea of troubles," << endl;
      cout << "And by opposing end them?" << endl;
      cout << "William Shakespeare" << endl;
      cout << "\nToo many bands locked down in the basement" << endl;
      cout << "Bought two flats and a loft extension" << endl;
      cout << "Too many .22s tucked in the car door" << endl;
      cout << "Looks like one of them Bond inventions (Brr, brr)" << endl;
      cout << "So many times I’ve dodged them cuffs" << endl;
      cout << "Good luck to the feds for the apprehension" << endl;
      cout << "Drank four pints and a grouse 2 litre" << endl;
      cout << "Now my brains in a new dimension" << endl;
      cout << "Came for the moolah, came for the paper" << endl;
      cout << "Came for the carnage, came for the dough" << endl;
      cout << "You don’t wanna come round here, get hit" << endl;
      cout << "Get left with a big name tag on the toe" << endl;
      cout << "Mary, Mary, quite contrary" << endl;
      cout << "How does your garden grow? (How does it grow mate?)" << endl;
      cout << "You already know" << endl;
      cout << "Grows in a big bando (Yeah good one Bas)" << endl;
      cout << "Pete & Bas" << endl;
      SetConsoleTextAttribute(hConsole, 4);
      cout << "\nEvery" << endl;
      SetConsoleTextAttribute(hConsole, 6);
      cout << "\tHunter" << endl;
      SetConsoleTextAttribute(hConsole, 7);
      cout << "\t\tWants" << endl;
      SetConsoleTextAttribute(hConsole, 10);
      cout << "\t\t\tto Know" << endl;
      SetConsoleTextAttribute(hConsole, 3);
      cout << "\t\t\t\tWhere" << endl;
      SetConsoleTextAttribute(hConsole, 9);
      cout << "\t\t\t\t\tSits" << endl;
      SetConsoleTextAttribute(hConsole, 5);
      cout << "\t\t\t\t\t\tPheasant" << endl;
      SetConsoleTextAttribute(hConsole, 15);
      cout << "Ïðîäàì öóöåíÿò." << endl;
      cout << "Ïîðîäà: ðîòâåéëåð." << endl;
      cout << "……" << endl;
      cout << "Òåë.: 222-22-22" << endl;
      cout << "222";
      cout << "\t|";
      SetConsoleTextAttribute(hConsole, 6);
      cout << "  222";
      SetConsoleTextAttribute(hConsole, 15);
      cout << "\t|";
      cout << "\n22";
      cout << "\t|";
      SetConsoleTextAttribute(hConsole, 6);
      cout << "  22";
      SetConsoleTextAttribute(hConsole, 15);
      cout << "\t|";
      cout << "\n22";
      cout << "\t|";
      SetConsoleTextAttribute(hConsole, 6);
      cout << "  22";
      SetConsoleTextAttribute(hConsole, 15);
      cout << "\t|";
      cout << "\n³ ò.ä." << endl;
      cout << R"(hello\nworld)";
      cout << R"("Test 'string'\t")";
      cout << R"((Such brackets))";
      int Age;
      Age = 34;
      const int Count_Days_in_Week = 7;
      cout << "\n";
      int DayIn_2000Year = 366;
      int HourInDay = 24;
      int HourIn_Year2000;
      HourIn_Year2000 = DayIn_2000Year * HourInDay;
      cout << "\t\t In 2000 year " << HourIn_Year2000;
      cout << " hours\n ";
      return 0; 
}